name = input('请输入您的姓名：')
gender = input('请输入您的性别：')
age = input('请输入您的年龄：')
school = input('请输入您的学校：')
print('正在生成您的简历....\n\n**********************************\n')
print('\t\t简历')
print('姓名：' + name)
print('性别：' + gender)
print('年龄：' + age)
print('学校：' + school)